name: Generate ASCII Artwork
on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Exceute Cowsay CMD 
              run: cowsay -f dragon "Run for cover, I am a Dragon.......RAWR" >> dragon.txt
             
            - name: Test File exists 
              run: grep -i "dragon" dragon.txt    
            
            
            - name: Read a File
              run: cat dragon.txt    

            - name: Checkout Repo
              run: ls -ltr    
            
    