name: My First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repo
              uses: actions/checkout@v4

            - name: run a msg
              run: | 
                echo "My first Job"
                ls -ltra
                cat README.md
            # Execute a Thrid party library
            - name: Generate ASCII Artwork 
              run: cowsay -f dragon "Run for cover, I am a Dragon.......RAWR" >> dragon.txt
              

            # - name: List files
            #   run: ls 
            
            # - name: Read files
            #   run: cat README.md
