name: Multi-Stage Pipeline Demo
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build stage
        run: echo "Building the code..."

  test:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test stage
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy stage
        run: echo "Deploying the application..."
 